name: Frontend Dev CI/CD

on:
  push:
    branches: [dev]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: alekaz04/coinkeeper/frontend

jobs:
  build-and-publish:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular application
        run: npm run build -- --configuration production

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GT_PAT }}

      - name: Build Docker image
        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev .

      - name: Push Docker image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev

      - name: Clean up old images
        run: docker image prune -af

  deploy-to-raspberry:
    runs-on: ubuntu-latest
    needs: build-and-publish
    if: success()
    steps:
      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.RASPBERRY_SSH_HOST }}
          username: ${{ secrets.RASPBERRY_SSH_USER }}
          password: ${{ secrets.RASPBERRY_SSH_PASSWORD }}
          port: ${{ secrets.RASPBERRY_SSH_PORT }}
          script: |
            # Переходим в директорию проекта
            cd /home/bl-server/dev/coinkeeper-api/CoinKeeper.Infrastructure/DockerCompose/Local

            # Останавливаем текущие контейнеры
            echo "Останавливаем контейнеры..."
            docker compose -f main.yml -p coinkeeper-dev down

            # Pull последнего образа
            echo "Загружаем последний образ..."
            docker compose -f main.yml -p coinkeeper-dev pull

            # Запускаем контейнеры
            echo "Запускаем контейнеры..."
            docker compose -f main.yml -p coinkeeper-dev up -d

            # Чистим старые образы
            echo "Очистка старых образов..."
            docker image prune -af

            echo "Деплой завершен успешно!"
